resource "aws_db_instance" "rds_database_instance" {
  count                       = "${var.create_rds ? 1 : 0}"
  identifier                  = "${var.identifier}"
  allocated_storage           = "${var.db_storage}"
  storage_type                = "${var.storage_type}"
  engine                      = "${var.engine}"
  engine_version              = "${var.engine_version}"
  instance_class              = "${var.instance_class}"
  name                        = "${var.name}"
  username                    = "${var.username}"
  password                    = "${var.password}"
  parameter_group_name        = "${var.parameter_group_name}"
  allow_major_version_upgrade = "${var.allow_major_version_upgrade}"
  apply_immediately           = "${var.apply_immediately}"
  auto_minor_version_upgrade  = "${var.auto_minor_version_upgrade }"
  multi_az                    = "${var.multi_az}"
  db_subnet_group_name        = "${var.db_subnet_group_name}"
  backup_retention_period     = "${var.backup_retention_period}"
  backup_window               = "${var.backup_window}"
  maintenance_window          = "${var.maintenance_window}"
  vpc_security_group_ids      = ["${var.security_group}"]
}
